services:

  master:
    image: bitnami/spark:3.5.0
    container_name: master
    environment:
      - SPARK_MODE=master
      #- SPARK_LOCAL_DIRS=/opt/bitnami/spark/logs

      # ------------ Don't Uncoment This:----------------
      #- SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/bitnami/spark/logs
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/opt/spark/data
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf 
      #- ./logs:/opt/bitnami/spark/logs   
    networks:
      - spark-network
  
  worker:
    image: bitnami/spark:3.5.0
    hostname: worker
    depends_on:
      - master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
    ports:
      - "8081-8083:8081"    # Up to 3 Workers
    volumes:
      - ./data:/opt/spark/data
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      # - ./logs:/opt/bitnami/spark/logs
    networks:
      - spark-network

  # jupyter: 
  #     image: jupyter/pyspark-notebook:x86_64-spark-3.5.0  
  #     container_name: jupyter
  #     ports:
  #       - "8888:8888"
  #     volumes:
  #       - ./jars:/opt/spark/jars
  #       - ./notebooks:/home/jovyan/work/notebooks
  #       # - ./logs:/home/jovyan/work/logs
  #     #  - ./data:/home/jovyan/work/data
  #     command: >
  #         bash -c "start-notebook.sh --NotebookApp.token=''"
  #     networks:
  #       - spark-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    networks:
      - spark-network

volumes:
  minio_data:

networks:
  spark-network:
    driver: bridge
