services:

  spark-master:
    image: ibrahimelaidouni/my-custom-spark:3.5.0
    hostname: spark-master
    container_name:
      spark-master
    environment:
      - SPARK_MODE=master
      - PYTHONPATH=/opt/spark
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file:
      - .env
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./common:/opt/spark/common
    networks:
      - spark-network
  
  spark-worker:
    image: ibrahimelaidouni/my-custom-spark:3.5.0
    hostname: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
      - PYTHONPATH=/opt/spark
    ports:
      - "8081-8083:8081"    # Up to 3 Workers or more, just adjust the range of ports
    env_file:
      - .env
    volumes:
      # - ./data:/opt/spark/data
      - ./common:/opt/spark/common
    networks:
      - spark-network

  jupyter-notebook: 
      image: ibrahimelaidouni/my-custom-jupyter:3.5.0  
      container_name: jupyter-notebook
      environment:
        - PYTHONPATH=/home/jovyan/work/common
      ports:
        - "8889:8888"
      env_file:
        - .env
      volumes:
        - ./notebooks:/home/jovyan/work/notebooks
        - ./data:/home/jovyan/work/data
        - ./common:/home/jovyan/work/common
      command: >
          bash -c "start-notebook.sh --NotebookApp.token=''"
      networks:
        - spark-network

  # spark-minio:
  #   image: minio/minio:latest
  #   container_name: spark-minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio_data:/data
  #   env_file:
  #     - .env
  #   command: server /data --console-address ":9001"
  #   networks:
  #     - spark-network

# volumes:
#   minio_data:

networks:
  spark-network:
    driver: bridge
